#!/usr/bin/env node
/*
 * Cloudflare build/deploy wrapper.
 *
 * Loads .env.cloudflare into the child process so Next.js sees every
 * NEXT_PUBLIC_* value during the build, and also generates a server-only
 * static fallback for Cloudflare runtime values.
 *
 * This makes the intended workflow:
 *   GitHub (project + .env.cloudflare) -> Cloudflare build -> Worker
 *
 * No Cloudflare Dashboard Variables/Secrets are required by this path.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const envFile = join(root, ".env.cloudflare");
const generated = join(root, "lib", "config", "cloudflare-static-env.generated.ts");

if (!existsSync(envFile)) {
  console.error("Missing .env.cloudflare. Create it before running the Cloudflare build.");
  process.exit(1);
}

function parseEnv(text) {
  const out = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    if (/^[A-Z][A-Z0-9_]*$/.test(key)) out[key] = value;
  }
  return out;
}

const values = parseEnv(readFileSync(envFile, "utf8"));
const childEnv = { ...process.env, ...values };

// Only server-side values are copied into the generated fallback.
const serverKeys = [
  "TMDB_TOKEN",
  "TMDB_API_KEY",
  "TMDB_API_BASE_URL",
  "TMDB_LANGUAGE",
  "TMDB_REGION",
  "SUPABASE_SERVICE_ROLE_KEY",
  "AD_PROVIDER_TAG",
];

const literal = (value) => JSON.stringify(value ?? "");
const generatedText = `// Generated by scripts/cf-build.mjs from .env.cloudflare.
import "server-only";

export const STATIC_CLOUDFLARE_ENV = {
${serverKeys.map((key) => `  ${key}: ${literal(values[key])},`).join("\n")}
} as const;
`;

writeFileSync(generated, generatedText, "utf8");

const command = process.platform === "win32" ? "npx.cmd" : "npx";
const args = process.argv.slice(2);
const result = spawnSync(command, args.length ? args : ["opennextjs-cloudflare", "build"], {
  cwd: root,
  env: childEnv,
  stdio: "inherit",
  shell: false,
});

process.exit(result.status ?? 1);
